In [1]:
import torch

In [8]:
a = [torch.rand(5), torch.rand(5), torch.rand(5)]

In [9]:
a

[tensor([0.7195, 0.0293, 0.5974, 0.1776, 0.8091]),
 tensor([0.1286, 0.0886, 0.2793, 0.6459, 0.1578]),
 tensor([0.5739, 0.3781, 0.5072, 0.9854, 0.6117])]

In [10]:
a = torch.stack(a, dim=0)

In [169]:
seq_dim = 2
b_dim = 3
n_class = 4
y = torch.tensor(range(2*3*4), dtype=torch.float).reshape(seq_dim,b_dim,n_class)
y, y.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]), torch.Size([2, 3, 4]))

In [170]:
y = y.transpose(0, 1).transpose(1,2)
y, y.shape

(tensor([[[ 0., 12.],
          [ 1., 13.],
          [ 2., 14.],
          [ 3., 15.]],
 
         [[ 4., 16.],
          [ 5., 17.],
          [ 6., 18.],
          [ 7., 19.]],
 
         [[ 8., 20.],
          [ 9., 21.],
          [10., 22.],
          [11., 23.]]]), torch.Size([3, 4, 2]))

In [158]:
y = y.transpose(1,2)
y, y.shape

(tensor([[[ 0., 12.],
          [ 1., 13.],
          [ 2., 14.],
          [ 3., 15.]],
 
         [[ 4., 16.],
          [ 5., 17.],
          [ 6., 18.],
          [ 7., 19.]],
 
         [[ 8., 20.],
          [ 9., 21.],
          [10., 22.],
          [11., 23.]]]), torch.Size([3, 4, 2]))

In [167]:
t= torch.zeros(seq_dim, b_dim, dtype=torch.long)
t[0,1] = 1
t[0,0] = 2
t[1,0] = 2
t[1,1] = 0
t

tensor([[2, 1, 0],
        [2, 0, 0]])

In [168]:
t = t.transpose(0, 1)
t

tensor([[2, 2],
        [1, 0],
        [0, 0]])

In [115]:
criterion = torch.nn.CrossEntropyLoss(reduction='none')
avg_criterion = torch.nn.CrossEntropyLoss()

In [118]:
cr = criterion(y, t)
cr

tensor([[0.1429, 2.1429],
        [0.0004, 0.1429],
        [4.1429, 4.1429]])

In [107]:
torch.log_softmax(y, dim=1)

tensor([[[ -4.1429,  -4.1429],
         [ -2.1429,  -2.1429],
         [ -0.1429,  -0.1429]],

        [[ -0.0004,  -4.1429],
         [-10.0004,  -2.1429],
         [ -8.0004,  -0.1429]],

        [[ -4.1429,  -4.1429],
         [ -2.1429,  -2.1429],
         [ -0.1429,  -0.1429]]])

In [117]:
avg_criterion(y,t)

tensor(1.7858)

In [8]:
a = torch.tensor([1,2,3,4])
a.shape

torch.Size([4])

In [10]:
b = torch.tensor([5])
b.shape

torch.Size([1])

In [12]:
torch.cat([a,b], dim=0)

tensor([1, 2, 3, 4, 5])